### Service-to-service invocation

###
GET http://localhost:5222/api/hero/villain/spiderman HTTP/1.1

###
GET http://localhost:5222/api/hero/villain/batman HTTP/1.1

###
GET http://localhost:5222/api/hero/villain/luke%20cage HTTP/1.1

###
GET http://localhost:5222/api/hero/villain/thor HTTP/1.1