version: '3'
services:
  ############################
  # tour of heroes api + dapr sidecar
  ############################
  tour-of-heroes-api:
    build: ~/Desktop/Dev/tour-of-heroes-dotnet-api
    ports:
      - "5222:5000"
    environment:
      - "DAPR_HTTP_PORT=3502"
      - "DAPR_GRPC_PORT=50002"
    depends_on:
      - redis
    networks:
      - tour-of-heroes-dapr
  tour-of-heroes-api-dapr:
    image: "daprio/daprd:edge"    
    command:
      [
        "./daprd",
        "-app-id",
        "tour-of-heroes-api",
        "-app-port",
        "5000",
        "-dapr-grpc-port",
        "50002",
        "-components-path",
        "/components"
      ]
    environment:
      - ConnectionString=Server=localhost,1433;Initial Catalog=heroes;Persist Security Info=False;User ID=sa;Password=Password1!
    volumes:
      - "./docker-compose-components:/components"      
    depends_on:
      - tour-of-heroes-api
    network_mode: "service:tour-of-heroes-api"
  ############################
  # tour of villains api + dapr sidecar
  ############################
  # tour-of-villains-api:
  #   build: ~/Desktop/Dev/tour-of-villains-api
  #   ports:
  #   - "5111:5000"
  #   environment:
  #     - "DAPR_HTTP_PORT=3501"
  #     - "DAPR_GRPC_PORT=50001"
  #   depends_on:
  #     - redis
  #   networks:
  #     - tour-of-heroes-dapr
  # tour-of-villains-api-dapr:
  #   image: "daprio/daprd:edge"
  #   command:
  #     [
  #       "./daprd",
  #       "-app-id",
  #       "tour-of-villains-api",
  #       "-app-port",
  #       "5120",
  #       "-dapr-grpc-port",
  #       "50001",
  #       "-components-path",
  #       "/components"
  #     ]
  #   volumes:
  #     - "/Users/gis/Desktop/Dev/tour-of-villains-api/docker-compose-components:/components"
  #   depends_on:
  #     - tour-of-villains-api
  #   network_mode: "service:tour-of-villains-api"
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - tour-of-heroes-dapr
  ############################
  # SQL Server
  ############################
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1!
      - MSSQL_PID=Express
    networks:
      - tour-of-heroes-dapr
  ###########################
  # Dapr dashboard
  ############################
  # dapr-dashboard:
  #   image: "ghcr.io/dapr/dashboard:latest"
  #   ports:
  #     - 8000:8080
  #   networks:
  #     - tour-of-heroes-dapr
networks:
  tour-of-heroes-dapr:
