apiVersion: v1
kind: Service
metadata:
  labels:
    app: tour-of-heroes-api
  name: tour-of-heroes-api
spec:
  type: NodePort
  ports:
    - name: web
      port: 5222
      targetPort: 5222
      nodePort: 30080
  selector:
    app: tour-of-heroes-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tour-of-heroes-api
  name: tour-of-heroes-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: tour-of-heroes-api
  template:
    metadata:
      labels:
        app: tour-of-heroes-api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "tour-of-heroes-api"
        dapr.io/app-port: "5222"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:     
        - image: ghcr.io/0gis0/tour-of-heroes-dotnet-api/tour-of-heroes-api-dapr:55e4cea
          name: tour-of-heroes-api
          ports:
          - containerPort: 5222
            name: web
