# https://opentelemetry.io/docs/collector/configuration/
receivers:
  otlp:
    protocols:
      grpc:
      http:

# Exporters send data to one or more backends or destinations
exporters:
  debug:
    # verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  azuremonitor:
    connection_string: "<INSTRUMENTATION_KEY>"
 
# A connector acts as an exporter to one pipeline and a receiver to another
connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [ 5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1000ms ]

# Processors are used to transform data
processors:
  resource:
    attributes:
      - action: insert
        key: service_name
        from_attribute: service.name
      - action: insert
        key: loki.resource.labels
        value: service_name

# Service pipelines define the flow of data through the collector
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ debug, otlp, spanmetrics, azuremonitor ]
    metrics:
      receivers: [ spanmetrics ]
      exporters: [ debug, prometheus, azuremonitor ]
    logs:
      receivers: [ otlp ]
      processors: [ resource ]
      exporters: [ debug, loki, azuremonitor ]