# https://opentelemetry.io/docs/collector/configuration/
receivers:
  otlp:
    protocols:
      grpc:
      http:

# Exporters send data to one or more backends or destinations
exporters:
  debug:
    # verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  # azuremonitor:
  #   connection_string: "InstrumentationKey=a7c817bc-3165-4afc-9c73-8985c04f4b48;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/"
 

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [ 5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1000ms ]

processors:
  resource:
    attributes:
      - action: insert
        key: service_name
        from_attribute: service.name
      - action: insert
        key: loki.resource.labels
        value: service_name

service:
  pipelines:
    # traces:
    #   receivers: [zipkin, otlp ]
    #   exporters: [ debug, otlp, spanmetrics ]
    # metrics:
    #   receivers: [ spanmetrics ]
    #   exporters: [ debug, prometheus ]
    # logs:
    #   receivers: [ otlp ]
    #   processors: [ resource ]
    #   exporters: [ debug, loki ]
    traces:
      receivers: [ otlp ]
      exporters: [ debug, otlp, spanmetrics ]
    metrics:
      receivers: [ spanmetrics ]
      exporters: [ debug, prometheus ]
    logs:
      receivers: [ otlp ]
      processors: [ resource ]
      exporters: [ debug, loki ]