apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: villain-pub-sub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: "passw0d!"