name: ⚙️ Continuous Integration

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/**"

jobs:
  build:   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 8.x
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
      
      - name: Test
        run: dotnet test --no-build --verbosity normal
      
      - name: Install coverlet
        run: dotnet tool install --global coverlet.console
      
      - name: Run tests with coverage        
        run: dotnet test --collect:"XPlat Code Coverage"
  
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.3
        with:
          reports: 'tests/TestResults/**/coverage.cobertura.xml' 
          targetdir: 'coveragereport' 
          reporttypes: 'MarkdownSummaryGithub;Badges'
      
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport 
          path: coveragereport 

      - name: Add comment to PR 
        if: github.event_name == 'pull_request'
        run: gh pr comment $PR_NUMBER --body-file coveragereport/SummaryGithub.md 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          
      - name: Publish coverage in build summary
        run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY # Adjust path and filename if necessary
        shell: bash