name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: tour-of-heroes-dotnet-api

jobs:

  build:   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: dotnet build and publish
      run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o './myapp'
    - name: Upload a build artifact
      uses: actions/upload-artifact@v2.3.0
      with:
        name: myapp
        path: ./myapp

  deploy:
    needs: [build]
    runs-on: self-hosted
    
    steps:
    - name: Say hello
      run: echo 'Hello you'

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: docker.pkg.github.com/0gis0/tour-of-heroes-dotnet-api/${{ env.IMAGE_NAME }}:latest
    
      
    
