name: IaC scans

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  checkov:
    permissions:
      contents: read
      security-events: write
    uses: 0GiS0/scan-tf-vulnerabilities/.github/workflows/checkov.yaml@main
  trivy:
    permissions:
      contents: read
      security-events: write
    uses: 0GiS0/scan-tf-vulnerabilities/.github/workflows/trivy.yaml@main
  terrascan:
    permissions:
      contents: read
      security-events: write
    uses: 0GiS0/scan-tf-vulnerabilities/.github/workflows/terrascan.yaml@main
  snyk:
    permissions:
      contents: read
      security-events: write
    uses: 0GiS0/scan-tf-vulnerabilities/.github/workflows/snyk.yaml@main
    with:
      working-directory: terraform
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
