name: Artifacts demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: tour-of-heroes-webapi
  AZURE_WEBAPP_PACKAGE_PATH: "."

jobs:
  iac:
    runs-on: ubuntu-latest    
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false #We need this to get the output
      - uses: actions/checkout@v2
      - name: Terraform init
        run: terraform init -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" -backend-config="access_key=${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"
      - name: Terraform plan
        run: terraform plan -out=tfplan
      - name: Terraform apply
        run: terraform apply tfplan"
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  build:
    needs: iac
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish --configuration Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp
      - name: "Upload artifact"
        uses: actions/upload-artifact@v2.3.0
        with:
          name: "myapp"
          path: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v2.1.0
        with:
          name: "myapp"
          path: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp"
      - name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp"
