using Microsoft.EntityFrameworkCore;

namespace tour_of_heroes_api.Models
{
    public class HeroContext : DbContext
    {
        public DbSet<Hero> Heroes { get; set; }

        public HeroContext(DbContextOptions<HeroContext> options) : base(options)
        {
            Database.EnsureCreated();
        }

        // This code was generated by GitHub Copilot 🤖
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Hero>().HasData(
                new Hero("Superman", "Clark Kent") { Id = 1, Description = "Man of Steel" },
                new Hero("Batman", "Bruce Wayne") { Id = 2, Description = "Dark Knight" },
                new Hero("Wonder Woman", "Diana Prince") { Id = 3, Description = "Amazonian Warrior" }
            );
        }        
    }
}